"""Add date to weather table

Revision ID: 03b25bc72395
Revises: 4f38ae452d6e
Create Date: 2017-03-13 23:14:53.927757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b25bc72395'
down_revision = '4f38ae452d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weathers', 'date')
    # ### end Alembic commands ###
